@startuml
class Elemento<T extends Comparable<T>>{
    - dato:T
    - siguiente:Elemento<T>
    + Elemento(dato:T)
    + getDato():T
    + setDato(dato:T):void
    + getSiguiente():Elemento<T>
    + setSiguiente(siguiente:Elemento<T>):void
}
class Pila<T extends Comparable<T>>{
    - cabeza:Elemento<T>
    + push(dato:T):void
    + pop():T
    + peek():T
    + isEmpty():boolean
}
Elemento *-- Pila
@enduml