@startuml
class Elemento<T extends Comparable<T>>{
    - dato:T
    - siguiente:Elemento<T>
    + Elemento(dato:T)
    + getDato():T
    + setDato(dato:T):void
    + getSiguiente():Elemento<T>
    + setSiguiente(siguiente:Elemento<T>):void
}
class Pila<T extends Comparable<T>>{
    - cabeza:Elemento<T>
    + push(dato:T):void
    + pop():T
    + peek():T
    + isEmpty():boolean
}
note right of Pila::push
**LIFO**: Apila al inicio
end note

note right of Pila::pop
**Elimina** y **devuelve** el primer elemento
end note

note left of Pila::isEmpty
**Devuelve** `true` si está vacía (`cabeza==null`)
end note

note left of Pila::peek()
**Devuelve** el primer elemento
end note
Elemento *-- Pila
@enduml