@startuml

interface Iterador<T> {
    + hasNext():boolean
    + next():T
}
class ElementoSE<T> {
    # dato: T
    # siguiente: ElementoSE<T>
    + ElementoSE(dato:T)
}
class IteradorLSE<T> {
    - actual: ElementoSE<T>
    + IteradorLSE(inicio:ElementoSE<T>)
    + hasNext():boolean
    + next():T
}
class ListaSimplementeEnlazada<T extends Comparable<T>> {
    # primero: ElementoSE<T>
    # tamaño: int
    + ListaSimplementeEnlazada()
    + add(dato:T):void
    + addFirst(dato:T):T
    + get(dato:T):T
    + del(dato:T):T
    + getAt(posicion:int):T
    + insertAt(posicion:int, dato:T):T
    + removeAt(posicion:int):T
    + isEmpty():boolean
    + getSize():int
    + getIterador():Iterador<T>
}
class LSEOrdenada<T extends Comparable<T>> {
    + add(dato:T):void
}
IteradorLSE ..|> Iterador : implements
LSEOrdenada --|> ListaSimplementeEnlazada : extends
ListaSimplementeEnlazada *-- ElementoSE : composición
IteradorLSE *-right- ElementoSE : actual
ListaSimplementeEnlazada ..> Iterador : retorna
@enduml